### ISSUE TITLE
navbar menu upgrade

### ISSUE THREAD

**Issue by satkar2001** [Nish251103/web-portfolio#1]
hey,i think it would be better if we keep the options that are currently in the menu in the navbar itself . and only when the screen size is decreased we will show the menu button . if you think this needs to be worked on, assign me the issue.

**Comment by Nish251103** [comment]
Hello @satkar2001 yes It would be better the way you suggested(menu button to show only with size decrease)
 but the thing is the site is not responsive for now. so it doesn't change the design when we decrease the size.

**Comment by Nish251103** [comment]
If you still want to try it you can do it in a new branch. I will merge it. Just let me know
