### ISSUE TITLE
Simple / basic animations

### ISSUE THREAD

**Issue by Nish251103** [Nish251103/web-portfolio#10]
The site is in plain text and does not have any effects. 
so any kind of effects you can add on texts or other items would be appreciated.

**Comment by mrvishalsharma** [comment]
i want to work on this issue...can you please assing me this issue? and if possible please provide some description

**Comment by mrvishalsharma** [comment]
can you just suggest me what type of text animation you want?

**Comment by Nish251103** [comment]
> can you just suggest me what type of text animation you want?

Any kind of animations are cool.
maybe text appearing with scrolling or something like that....
