### ISSUE TITLE
Improve scrolling bar

### ISSUE THREAD

**Issue by Nish251103** [Nish251103/web-portfolio#11]
The Scrolling bar is default and does not go with the theme(dark).
If you could change it.

**Comment by mrvishalsharma** [comment]
i want to work on this issue...can you please assing me this issue?  and if possible please provide some description

**Comment by mrvishalsharma** [comment]
@Nish251103 i have completed this task.....just before pushing it to your branch please check this out and please confirm me back is it ok or do i need to change anything more in the scroll bar:-[ MyPortfolio](https://www.awesomescreenshot.com/video/5482085)

**Comment by Nish251103** [comment]
> @Nish251103 i have completed this task.....just before pushing it to your branch please check this out and please confirm me back is it ok or do i need to change anything more in the scroll bar:-[ MyPortfolio](https://www.awesomescreenshot.com/video/5482085)

Hey, It says invalid share key. I cant see it.

**Comment by mrvishalsharma** [comment]
> 
> 
> > @Nish251103 i have completed this task.....just before pushing it to your branch please check this out and please confirm me back is it ok or do i need to change anything more in the scroll bar:-[ MyPortfolio](https://www.awesomescreenshot.com/video/5482085)
> 
> Hey, It says invalid share key. I cant see it.

just visit this link once again [MyPortfolio](https://www.awesomescreenshot.com/video/5482085?key=6b206f3eb9e3cafeac56c268e9dc7f69)

**Comment by mrvishalsharma** [comment]
Just visit this link once again [MyPortfolio](https://www.awesomescreenshot.com/video/5482085?key=6b206f3eb9e3cafeac56c268e9dc7f69)

**Comment by Nish251103** [comment]
@mrvishalsharma It's perfect.
There were recent updates in other files, So Kindly open the PR with updated files, I could merge it right away.
Thank you 😃
