### ISSUE TITLE
Fill-up / design empty spaces.

### ISSUE THREAD

**Issue by Nish251103** [Nish251103/web-portfolio#12]

**Comment by mrvishalsharma** [comment]
i want to work on this as well can you provide me some description about what you want to add on this empty spaces

**Comment by Nish251103** [comment]
I don't exactly know, anything that you seem appropriate would be perfect...
maybe icons representing education, portfolio, developer, or something like that

**Comment by mrvishalsharma** [comment]
> 
> 
> I don't exactly know, anything that you seem appropriate would be perfect... maybe icons representing education, portfolio, developer, or something like that

ok i will add some custom images from my side and i will send you those screen short and then you confirm me back if it is ok or not

**Comment by Nish251103** [comment]
Okay
Thank You

**Comment by mrvishalsharma** [comment]
![image](https://user-images.githubusercontent.com/81310468/135887876-344c5224-b6a2-4857-95e9-39dc1a943d24.png)
Is It looking good??

**Comment by Nish251103** [comment]
> ![image](https://user-images.githubusercontent.com/81310468/135887876-344c5224-b6a2-4857-95e9-39dc1a943d24.png) Is It looking good??

yesss!!!

**Comment by mrvishalsharma** [comment]
I have complete this task just visit this link once to see your whole [Portfolio website]( https://www.awesomescreenshot.com/video/5493106?key=95d328c8af0af2ab8e83c44d950ff9fa) and if you like it and i will send you pull request

**Comment by Nish251103** [comment]
It's Amazing.
You may send the Pull Request.

**Comment by mrvishalsharma** [comment]
> 
> 
> It's Amazing. You may send the Pull Request.

I think i did something wrong while sending you  pull request so before accepting my pull request just have a look in the code and see the changes ....i think i did something wrong

**Comment by Nish251103** [comment]
> > It's Amazing. You may send the Pull Request.
> 
> I think i did something wrong while sending you pull request so before accepting my pull request just have a look in the code and see the changes ....i think i did something wrong and if anything is wrong then i wll clone your repo again and after that i will make the changes and send you again pull request

If you are referring to conflicts I will correct that, It's because of multiple updates and you didn't do anything wrong.
Anyways Thank you so much 😃

**Comment by mrvishalsharma** [comment]
you most welcome... i really enjoyed makeing it.
