### ISSUE TITLE
Messed up Merges

### ISSUE THREAD

**Issue by Nish251103** [Nish251103/web-portfolio#24]
I messed up PR Merges due to multiple Contributors working simultaneously.
I tried to resolve a few conflicts but messed up the rest.

**Comment by parth-panchal** [comment]
Looks like you could use a contributing guide for this repository for contributors which would have a detailed explanation about how to contribute here. If you could assign me this issue, I could draft it up for you so that the same problem doesn't happen again.

**Comment by Nish251103** [comment]
> Looks like you could use a contributing guide for this repository for contributors which would have a detailed explanation about how to contribute here. If you could assign me this issue, I could draft it up for you so that the same problem doesn't happen again.

That would be great...
Thank You 😃
