### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by Anushh23** [Nish251103/web-portfolio#32]
Hey, can I add a scroll to top button.

similar to this one:
![scroll to top](https://user-images.githubusercontent.com/88843413/136041144-bc99162b-1cce-42d0-b31e-1bd9ded68c75.png)

**Comment by Nish251103** [comment]
Hello @Anushh23, 
Yes, It would be good. 😃

**Comment by Anushh23** [comment]
@Nish251103 made the PR kindly review.
