### ISSUE TITLE
Favicon and scroll to top

### ISSUE THREAD

**Issue by Khushboo288** [Nish251103/web-portfolio#42]
This page needs to improve it footer and a scroll to top button at last which makes the page much better and easy to use.

**Comment by Khushboo288** [comment]
I can improve your page Please assign this to me.

**Comment by Khushboo288** [comment]
I can improve your page Please assign this to me.
Fotter of page does not contain proper favicon icons. I will improve  it.

**Comment by Khushboo288** [comment]
ok Ty. Will complete your work soon

**Comment by Khushboo288** [comment]
I have competed yr work but plz add hacktoberfest 2021 label to this issue. I m hacktobrfest contributer, so please add yr project to hactoberfest so that my work gets counted. After you do so, I will make a pull request.

**Comment by Nish251103** [comment]
it doesnt matter if the label is in the issue. It only counts if the label is in the PR.

**Comment by Khushboo288** [comment]
ok so my work will be counted in hactoberfest, Right

**Comment by Khushboo288** [comment]
I will create a pull request soon.

**Comment by Nish251103** [comment]
> I will create a pull request soon.

yes if the PR has the hacktoberfest label

**Comment by Khushboo288** [comment]
Completed the issue, plz review and merge Pr #47 and Pr #48. 
47 contains html and 48 contains css.
