### ISSUE TITLE
Blogging Page

### ISSUE THREAD

**Issue by Nish251103** [Nish251103/web-portfolio#5]

**Comment by varunsh17** [comment]
Would like to work upon it . 
please assign it .

**Comment by varunsh17** [comment]
Hey can you please open another issue because your portfolio has also horizontal scrolling and grids are not customized properly

**Comment by Nish251103** [comment]
Okay, give a minute.

**Comment by Nish251103** [comment]
@varunsh17 I have added the issue #9
If you reply there I will be able to assign it to you

**Comment by varunsh17** [comment]
I am starting to work upon it , can you tell me what is blogging page in it ?

**Comment by Nish251103** [comment]
Something like these but you can design any way you want as long as the theme is dark. 
![image](https://user-images.githubusercontent.com/71500515/135814423-efac15af-c261-4eba-b5e9-c5c4b8518479.png)

![image](https://user-images.githubusercontent.com/71500515/135814660-c7081dc4-c712-4249-ba4b-b6a7b5d36533.png)

**Comment by Nish251103** [comment]
I was thinking of creating a new file(blog.html) and then linking it to the navbar(index.html)

**Comment by varunsh17** [comment]
Ok then I will create the new file with this theme as you have given .. You cam merge that yourself I believe .

**Comment by Nish251103** [comment]
> Ok then I will create the new file with this theme as you have given .. You cam merge that yourself I believe .

Okayy. 😃
