### ISSUE TITLE
Responsive 

### ISSUE THREAD

**Issue by baibhav0305** [Nish251103/web-portfolio#7]
hey I can try to make this responsive
can you assign me this issue

**Comment by varunsh17** [comment]
I would like to work upon it please assign it

**Comment by varunsh17** [comment]
May I know why did you closed it ?

**Comment by Nish251103** [comment]
This issue is been fixed.
It's just that the contributor forgot to mention it in the PR.
and also I messed up few merges.

**Comment by Nish251103** [comment]
@varunsh17 
If you are working on it, you may reopen it.

**Comment by varunsh17** [comment]
yes buddy I am working !

**Comment by varunsh17** [comment]
You should read this article it covers all important topics for portfolio ..
Link -> https://www.freecodecamp.org/news/how-to-build-a-developer-portfolio-website/

Just helping you to get better . Please don't consider it in bad way 🙂

**Comment by Nish251103** [comment]
> You should read this article it covers all important topics for portfolio .. Link -> https://www.freecodecamp.org/news/how-to-build-a-developer-portfolio-website/
> 
> Just helping you to get better . Please don't consider it in bad way 🙂

Thank you for the article I will go through it.
with college going on I didn't have much time to work on it.
DW I don't take anything in a bad way 😃

**Comment by Shiyasmohd** [comment]
can i work on this?

**Comment by varunsh17** [comment]
> can i work on this?

I am already on it buddy , you can look at others out there 🙂

**Comment by Nish251103** [comment]
> can i work on this?

Varunsh17 already working on it.

**Comment by varunsh17** [comment]
Will give you pull request once I am done because it may take time as it must be accurate ..

**Comment by Nish251103** [comment]
> Will give you pull request once I am done because it may take time as it must be accurate ..

Okay, no hurry😊
